[pytest]
addopts = -v --tb=short --log-cli-level=INFO --html=reports/report.html --self-contained-html --css=tests/assets/style.css
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
