# -*- coding: utf-8 -*-
"""dental_convolutional_neural_network_v3 (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x5hoq4NiSqaV7vW-TL9nhB7aFQOJtPyb

# Convolutional Neural Network

### Importing the libraries
"""

!pip install git+https://github.com/jacobgil/pytorch-grad-cam.git -q

import os
import shutil
from glob import glob
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image, ImageDraw # Added ImageDraw
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import torch.cuda.amp as amp
from torchvision.models import efficientnet_b3
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
import warnings
warnings.filterwarnings("ignore")

random.seed(42)
torch.manual_seed(42)
np.random.seed(42)

from google.colab import drive
drive.mount('/content/drive/')

original_dirs = {
    'calculus': '/content/drive/MyDrive/dataset/calculus',
    'cancers': '/content/drive/MyDrive/dataset/cancers',
    'gingivitis': '/content/drive/MyDrive/dataset/gingivitis',
    'ulcers': '/content/drive/MyDrive/dataset/mouth_ulcer',
    'olp': '/content/drive/MyDrive/dataset/oral_lichen_planus'
}

# --- Discover images and create initial DataFrame ---
print("--- Discovering image files ---")
filepaths = []
labels = []
for label, path in original_dirs.items():
    # Using glob to find all image files, including subdirectories if any
    image_files = glob(os.path.join(path, '**', '*.jpg'), recursive=True) + \
                  glob(os.path.join(path, '**', '*.jpeg'), recursive=True) + \
                  glob(os.path.join(path, '**', '*.png'), recursive=True)

    # Filter out any problematic filenames like those starting with '._'
    image_files = [f for f in image_files if not os.path.basename(f).startswith('._')]

    filepaths.extend(image_files)
    labels.extend([label] * len(image_files))
    # print(filepaths)
    # print(labels)
    print(f"Found {len(image_files)} images for class: {label}")

df_full = pd.DataFrame({'filepath': filepaths, 'label': labels})
print(f"\nOriginal full dataset shape: {df_full.shape}")
print("Original class distribution:\n", df_full['label'].value_counts())

# --- DATA BALANCING ---
print("\n--- Applying Data Balancing ---")
class_counts = df_full['label'].value_counts()
print(class_counts)
M_ni_values = class_counts.values
C = len(class_counts)
M_total = np.sum(M_ni_values)
K = int(round(M_total / C)) # Target number of images per class

print(f"Total original images (M_total): {M_total}")
print(f"Number of classes (C): {C}")
print(f"Target K (mean images per class, rounded): {K}")

balanced_dfs_list = []
for class_label, count in class_counts.items():
    class_df = df_full[df_full['label'] == class_label]
    if count < K:
        num_to_add = K - count
        print(f"Class '{class_label}': Count ({count}) < K ({K}). Oversampling by duplicating {num_to_add} samples.")
        additional_samples = class_df.sample(n=num_to_add, replace=True, random_state=42)
        balanced_dfs_list.append(pd.concat([class_df, additional_samples]))
    else: # count >= K
        print(f"Class '{class_label}': Count ({count}) >= K ({K}). Undersampling to {K} samples.")
        downsampled_df = class_df.sample(n=K, replace=False, random_state=42)
        balanced_dfs_list.append(downsampled_df)

df_balanced = pd.concat(balanced_dfs_list).reset_index(drop=True)
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print("\nBalanced class distribution (before expansion):")
print(df_balanced['label'].value_counts())
print(f"Total images after balancing: {len(df_balanced)}")

# --- DATASET EXPANSION ---
print("\n--- Applying Dataset Expansion ---")
df_original = df_balanced.copy()
df_original['apply_flip'] = False
df_original['apply_mask'] = False
print(f"Segment 1 (Original): {len(df_original)} images")

df_flipped = df_balanced.copy()
df_flipped['apply_flip'] = True
df_flipped['apply_mask'] = False
print(f"Segment 2 (Flipped): {len(df_flipped)} images")

df_masked_original = df_balanced.copy()
df_masked_original['apply_flip'] = False
df_masked_original['apply_mask'] = True
print(f"Segment 3 (Masked Original): {len(df_masked_original)} images")

df_masked_flipped = df_balanced.copy()
df_masked_flipped['apply_flip'] = True
df_masked_flipped['apply_mask'] = True
print(f"Segment 4 (Masked Flipped): {len(df_masked_flipped)} images")

df_expanded = pd.concat([df_original, df_flipped, df_masked_original, df_masked_flipped], ignore_index=True)
df_expanded = df_expanded.sample(frac=1, random_state=42).reset_index(drop=True)
print(f"\nTotal images after expansion: {len(df_expanded)}")


# --- Label Encoding and Splitting ---
label_encoder = LabelEncoder()
df_expanded['label_encoded'] = label_encoder.fit_transform(df_expanded['label'])
CLASSES = label_encoder.classes_.tolist()
NUM_CLASSES = len(CLASSES)
idx_to_class = {i: cls_name for i, cls_name in enumerate(CLASSES)}
print(f"\nClasses after encoding: {CLASSES}")

# Create a held-out test set FIRST from the expanded data
train_val_df, test_df = train_test_split(
    df_expanded,
    test_size=0.2,
    random_state=42,
    stratify=df_expanded['label_encoded']
)

# Then create train and validation sets from the remaining data
train_df, val_df = train_test_split(
    train_val_df,
    test_size=0.1,
    random_state=42,
    stratify=train_val_df['label_encoded']
)

print(f"\nTraining data shape: {train_df.shape}")
print(f"Validation data shape: {val_df.shape}")
print(f"Test data shape: {test_df.shape}")

print("\nFinal training set distribution:")
print(train_df['label'].value_counts(normalize=True))

"""## Part 1 - Data Preprocessing

### Preprocessing the Training set

### Circular Masking
"""

class CircularMask:
    def __call__(self, img):
        # img is a PIL Image
        width, height = img.size
        mask = Image.new('L', (width, height), 0) # 'L' for grayscale mask
        draw = ImageDraw.Draw(mask)
        # Draw a white circle in the center, inscribed in the smaller dimension
        diameter = min(width, height)
        # Calculate top-left and bottom-right coordinates for the ellipse (circle)
        # to be centered
        left = (width - diameter) / 2
        top = (height - diameter) / 2
        right = left + diameter
        bottom = top + diameter
        draw.ellipse((left, top, right, bottom), fill=255)

        img_masked = Image.new('RGB', (width, height), (0, 0, 0)) # Create a black background
        # Ensure image is RGB before pasting, common issue with PNGs having alpha
        if img.mode != 'RGB':
            img = img.convert('RGB')
        img_masked.paste(img, (0,0), mask) # Paste original image using the circular mask
        return img_masked

"""##Data augmentation with Circular Mask"""

train_transforms = transforms.Compose([
    CircularMask(),  # Apply circular mask first
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_transforms = transforms.Compose([
    CircularMask(),  # Apply circular mask first
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

"""##Load Data Set"""

class DentalDataset(Dataset):
    def __init__(self, df, transform=None):
        self.df = df.reset_index(drop=True)
        self.transform = transform

        self.filepaths = self.df['filepath'].values
        self.labels = self.df['label_encoded'].values

        # Get flags for conditional augmentation from the dataframe
        self.apply_flip_flags = self.df['apply_flip'].values
        self.apply_mask_flags = self.df['apply_mask'].values

        self.circular_mask_processor = CircularMask()

    def __len__(self):
        return len(self.filepaths)

    def __getitem__(self, idx):
        img_path = self.filepaths[idx]
        try:
            image = Image.open(img_path).convert('RGB')
        except FileNotFoundError:
            print(f"ERROR: File not found {img_path}")
            # Return a placeholder tensor
            image = Image.new('RGB', (224, 224), color = 'red')
            # The main training loop will skip batches with this dummy label
            return self.transform(image), torch.tensor(-1, dtype=torch.long)

        # Apply conditional augmentations BEFORE the main transform pipeline
        # These operations are on PIL Images
        if self.apply_mask_flags[idx]:
            image = self.circular_mask_processor(image)

        if self.apply_flip_flags[idx]:
            image = transforms.functional.hflip(image)

        # Apply the main augmentation/preprocessing pipeline
        if self.transform:
            image = self.transform(image)

        label = torch.tensor(self.labels[idx], dtype=torch.long)
        return image, label

train_dataset = DentalDataset(train_df, transform=train_transforms)
val_dataset = DentalDataset(val_df, transform=val_transforms)
test_dataset = DentalDataset(test_df, transform=val_transforms)

"""##Data loaders with optimized settings"""

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

"""## Define EfficientNet-B3 model"""

class CustomEfficientNet(nn.Module):
    def __init__(self, num_classes):
        super(CustomEfficientNet, self).__init__()
        self.model = efficientnet_b3(weights='EfficientNet_B3_Weights.IMAGENET1K_V1')
        self.model.classifier = nn.Sequential(
            nn.Dropout(0.4), # Original dropout was 0.3 for B3, 0.4 is fine
            nn.Linear(self.model.classifier[1].in_features, num_classes)
        )

    def forward(self, x):
        return self.model(x)

"""## Initialize Model"""

num_classes = 5
print(num_classes)
model = CustomEfficientNet(num_classes)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model.to(device)

"""### Optimizer and loss"""

optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=3)

"""### Mixed precision scaler"""

scaler = amp.GradScaler()

"""### Training loop with mixed precision"""

num_epochs = 30 # Reduced for quicker demonstration, you can set it back to 50
best_val_loss = float('inf')
patience = 15 # Early stopping patience
epochs_no_improve = 0

train_losses, val_losses, train_accuracies, val_accuracies = [], [], [], []

for epoch in range(num_epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        with amp.autocast(): # Enables mixed precision
            outputs = model(inputs)
            loss = criterion(outputs, labels)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        running_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_dataset)
    epoch_acc = correct / total
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_acc)

    # Validation
    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            with amp.autocast(): # Mixed precision for validation too
                outputs = model(inputs)
                loss = criterion(outputs, labels)
            val_loss += loss.item() * inputs.size(0)
            _, predicted = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    epoch_val_loss = val_loss / len(val_dataset)
    epoch_val_acc = val_correct / val_total
    val_losses.append(epoch_val_loss)
    val_accuracies.append(epoch_val_acc)

    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {epoch_loss:.4f}, Train Acc: {epoch_acc:.4f}, Val Loss: {epoch_val_loss:.4f}, Val Acc: {epoch_val_acc:.4f}')

    scheduler.step(epoch_val_loss)

    # Early stopping
    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        epochs_no_improve = 0
        torch.save(model.state_dict(), 'best_model_masked.pth')
        print(f'New best model saved with validation loss: {best_val_loss:.4f}')
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print(f'Early stopping triggered after {epoch+1} epochs.')
            break

# Load best model
model.load_state_dict(torch.load('best_model_masked.pth'))

"""### Test-Time Augmentation"""

def tta_predict(model, loader, device, num_augmentations=5):
    model.eval()
    test_preds_tta, test_true_tta = [], []

    # Define TTA-specific augmentations (applied to PIL images)
    # These are applied to images already masked by the loader's val_transform
    tta_pil_augmentations = transforms.Compose([
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        # Add other geometric augmentations if desired
    ])

    # Define the final ToTensor and Normalize transform
    to_tensor_and_normalize = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    with torch.no_grad():
        for inputs, labels in loader:
            # Inputs are already masked, resized, cropped, and normalized by the DataLoader
            batch_outputs_sum = torch.zeros(inputs.size(0), num_classes).to(device)

            # 1. Prediction on the original (transformed) image from loader
            with amp.autocast():
                outputs = model(inputs.to(device))
            batch_outputs_sum += outputs.softmax(dim=1)

            # 2. Predictions on augmented versions
            # Denormalize to get PIL images for TTA augmentations
            mean = torch.tensor([0.485, 0.456, 0.406], device=device).view(1, 3, 1, 1)
            std = torch.tensor([0.229, 0.224, 0.225], device=device).view(1, 3, 1, 1)

            for i in range(inputs.size(0)): # Process each image in the batch
                original_tensor_normalized = inputs[i].unsqueeze(0).to(device) # Keep original normalized tensor for later

                # Denormalize current image
                denorm_tensor = inputs[i].cpu() * std.cpu().squeeze()[:, None, None] + mean.cpu().squeeze()[:, None, None]
                denorm_tensor = denorm_tensor.clamp(0, 1)
                pil_image = transforms.ToPILImage()(denorm_tensor)

                for _ in range(num_augmentations -1): # -1 because one prediction is from original input
                    augmented_pil = tta_pil_augmentations(pil_image)
                    augmented_tensor = to_tensor_and_normalize(augmented_pil).unsqueeze(0).to(device)
                    with amp.autocast():
                        outputs_aug = model(augmented_tensor)
                    batch_outputs_sum[i] += outputs_aug.squeeze().softmax(dim=0) # Accumulate for current image

            avg_preds = batch_outputs_sum / num_augmentations # Average predictions
            _, predicted_labels = torch.max(avg_preds, 1)

            test_preds_tta.extend(predicted_labels.cpu().numpy())
            test_true_tta.extend(labels.cpu().numpy())

    return test_true_tta, test_preds_tta

# Evaluate with TTA
print("\nEvaluating with Test-Time Augmentation...")
test_true, test_preds = tta_predict(model, test_loader, device, num_augmentations=5)
test_acc_tta = accuracy_score(test_true, test_preds)
print(f'Test Accuracy with TTA: {test_acc_tta:.4f}')

"""### Plotting loss and accuracy"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5)) # Adjusted size
ax1.plot(train_losses, label='Train Loss')
ax1.plot(val_losses, label='Validation Loss')
ax1.set_title('Loss Curves')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True)

ax2.plot(train_accuracies, label='Train Accuracy')
ax2.plot(val_accuracies, label='Validation Accuracy')
ax2.set_title('Accuracy Curves')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Accuracy')
ax2.legend()

ax2.grid(True)
plt.tight_layout()
plt.show()

"""## Classification report and confusion matrix"""

class_names = label_encoder.classes_.tolist()
print("\nClassification Report (with TTA):")
print(classification_report(test_true, test_preds, target_names=class_names, digits=4))

conf_mat = confusion_matrix(test_true, test_preds)
plt.figure(figsize=(8, 7)) # Adjusted size
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix (with TTA)')
plt.show()